apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  # this translates to the name of the statefulset that is created
  name: cockroachdb
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "60Gi"
        volumeMode: Filesystem
  resources:
    requests:
      cpu: 3
      memory: 12Gi
    limits:
      cpu: 3
      memory: 12Gi
  tlsEnabled: true
# You can set either a version of the db or a specific image name
# cockroachDBVersion: v21.1.11
  image:
    name: cockroachdb/cockroach:v22.1.3
  # nodes refers to the number of crdb pods that are created
  # via the statefulset
  nodes: 3
  additionalLabels:
    crdb: is-cool
---
apiVersion: v1
kind: Service
metadata:
  name: crdb-lb
  labels:
    app: cockroachdb
spec:
  selector:
    app.kubernetes.io/name: cockroachdb
  ports:
  - protocol: "TCP"
    port: 8080
    name: dbconsole
  - protocol: "TCP"
    port: 26257
    name: sql
  type: LoadBalancer

