apiVersion: v1
kind: Service
metadata:
  name: crdb-geo-tourist-lb
spec:
  selector:
    app: crdb-geo-tourist
  ports:
  - protocol: "TCP"
    port: 80 
    targetPort: 18080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crdb-geo-tourist
spec:
  selector:
    matchLabels:
      app: crdb-geo-tourist
  replicas: 2
  template:
    metadata:
      labels:
        app: crdb-geo-tourist
    spec:
      containers:
      - name: crdb-geo-tourist
        image: mgoddard/crdb-geo-tourist:1.0
        imagePullPolicy: Always
        env:
          - name: PGHOST
            value: "cockroachdb-public"
          - name: PGPORT
            value: "26257"
          - name: PGDATABASE
            value: "defaultdb"
          - name: PGUSER
            value: "root"
          - name: PGPASSWORD
            value: ""
          - name: MAPBOX_TOKEN
            value: "INSERT YOUR MAPBOX TOKEN VALUE HERE"
          - name: USE_GEOHASH
            value: "True"
        ports:
        - containerPort: 18080
      restartPolicy: Always

