apiVersion: v1
kind: Service
metadata:
  name: crdb-db-console-lb
spec:
  selector:
    #app: cockroachdb
    app.kubernetes.io/name: cockroachdb
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer

